### ISSUE TITLE
running postgres in bin/up

### ISSUE THREAD

**Issue by bbrock25** [spartansystems/raygun-rails-template#2]
do we want to have the bin/up script manage the postgres connection?

**Comment by jasontwong** [comment]
I would say no. It's not isolated enough to the app.

**Comment by Mrjaco12** [comment]
What do you mean by postgres connection? I know that we've used it to start the postgres process before and I liked that, but I don't know about managing connections.

**Comment by bbrock25** [comment]
I meant process. I typically let OSX just run postgres for me.

**Comment by Mrjaco12** [comment]
I think the idea of starting it up in a script is for simplicity for folks who don't care to know how to start a handful of different tools on the command line. Keep in mind the bin/up script is totally optional and if yo want to run:

`postgres -D tmp/postgres`
`rails s`

manually then go ahead.

**Comment by bbrock25** [comment]
Thanks, I'm aware. I still think that running the process in that script is outside of what that bin/up script should be doing. IMHO it should manage the rails processes and nothing else.

**Comment by Mrjaco12** [comment]
Why would we limit it like that? Is there a best practices guide for this sort of thing? I would agree with you if there was some level of variability in the db but there's not really right now.

**Comment by Mrjaco12** [comment]
As I understand, we actually want bin/up to be the one stop shop for getting your app running without having to manage anything else. Taking postgres out would make that impossible. And given that line of reasoning, what types of other processes would the bin/up script manage?

**Comment by bbrock25** [comment]
Yes, I see what you're saying. My issue is that I wouldn't want to have multiple postgres processes running on my machine, and I assume that many of the other folks at spartan already have a db running in the background and would feel the same.

Managing a postgres process like this isn't really standard, and possibly more difficult to diagnose for those unfamiliar. Maybe we just recommend running
```
bundle exec rails s
```

**Comment by Mrjaco12** [comment]
Ok. We can update the documentation to inform users that running bin/up creates a new postgres process and if you don't want that then you can run postgres yourself and use bin/rails s or bundle exec rails s. And leave this tool in for those who aren't running a background postrgres somewhere and want a simple start and stop for their app.

**Comment by squaresurf** [comment]
`bin/up` should start everything necessary for a front end dev to be able to get to work.

**Comment by bbrock25** [comment]
What more does a front end dev need than a rails server? Most everyone will already have a db running on their system. I think that the devs are in the minority here in that they might want to have the db configured a unique way from project to project; an opinion that is currently being imposed here through the readme and this script in question.

Additionally, obscuring a simple startup command doesn't encourage people to understand underlying tooling. Everyone working on rails projects will need to issue rails specific commands to manage the evolution of the database either way.

In the end, I have less issue with the script in-particular, as it is _optional_. I just don't agree with this as a default for how a project should be setup and ran for someone who is unfamiliar with rails.

**Comment by Mrjaco12** [comment]
I disagree with the statement that "most everyone will already have a db running on their system". I guess that's the assumption behind this script is that the above statement isn't true. We assume you aren't running anything locally including DB, cache, background job service. We need to validate which line of thinking is accurate before continuing this discussion.

**Comment by squaresurf** [comment]
I'm with @Mrjaco12 on this.

**Comment by bbrock25** [comment]
Well, the script does assume that postgres is already installed, I don't think that a far jump to assume that the db is running. As I see it, the db and webserver are completely different services and this project should be a formal definition of how we do / run rails, not postgres.

**Comment by squaresurf** [comment]
There are a few benefits by having the default postgres service running in a process like this:

* Resources aren't wasted on postgres when you're not using it.
* The space used by your db is cleaned up when you remove the project (the db is stored in db/postgres).
* There is no need to manage service start and stop with launchd etc, (which is not always a trivial task).
* You don't need to create any postgres users since the server can run with no auth needed.

It's also good to note that I did a typical install of postgres with brew and it did not setup a global running process for me (not that I wanted it too). So I disagree with your assumption that if postgres is installed then it must be running.

In the end, the real point of this is not managing postgres or not, but that no matter what project/tech stack we use we should always have a `bin/up` that will get all necessary services running. Since we do / run rails with postgres in dev and production having postgres running is a necessary service for a dev environment. I envision that `bin/up` will also start up redis, memcache and any other services that are needed to have a functioning dev environment for our base rails stack.

Here are some definitions that I see for helping with dev environment consistency. You can see some examples of this in my latest PR #10.

* `bin/init` will setup anything necessary for you to run `bin/up`.
* `bin/up` will start all necessary processes for a dev environment.
* `bin/down` will stop anything that might not have been stopped if `bin/up` crashes.

**Comment by bbrock25** [comment]
I do see the benefits of having this collection of scripts, but I wonder if its really the consensus on best way to manage these local processes that we rely on. Is this how you typically manage your rails processes, and if so, what are the benefits of using this over [foreman](https://github.com/ddollar/foreman) as we discussed previously? There are plenty of good tools out there for managing multiple services, why do we need our own collection of bash scripts?

I know that this is splitting hairs, but when we spin up a new project with the directions found in this readme, this is what we'll be supporting from project to project. Do we really NEED a collection of devops scripts to manage something as simple as starting and stopping development servers? Do we really need to abstract the tools away so that folks don't need to know their running a rails server and a database? Will this really make things easier for everyone than if they just started the servers manually?

**Comment by bbrock25** [comment]
If I'm truly a minority here, that's fine, we can close the issue, but I do think that it requires more thought than those involved here as this is the basis for all of our projects going forward. @jasontwong @samcdavid @handerson do you have any feelings about this? if not, I'll close the issue and move on to submitting PR's :smile_cat:

**Comment by squaresurf** [comment]
Foreman might be the best tool in the end which shows the exact reason why these scripts are so useful. It give us the ability to change to best practices without having to teach everyone the new way **before** they can get the benefit of the new and improved. If we use Foreman, I will still argue that we **must** have these scripts. The scripts are bigger than rails since you can then clone, bin/init, and bin/up on any project no matter the tech stack and be on your way. That then opens the door for anyone to try things locally if they'd like, such as product advisors, clients, etc.

Now the big difference between the scripts and foreman is that the main rails server still gets stdin whereas foreman doesn't pass it along, requiring tools like remote pry.

As for requiring everyone to learn everything, I disagree. These scripts don't just abstract how things run, but are an example for how you could do it yourself as it codifies the process. They can be used as a teaching tool. I love that I could just crack open a script and see how thing work if I'd like.

I feel **strongly** that we should be running as close to same environment as production as possible. For example, running redis for feature flippers as well as active jobs allows everyone on the team to test how their changes affect the codebase holistically. So yes, designers should run all the services, which shouldn't be difficult if you have these scripts.

Lastly, if you don't wanna learn bash for some reason, the scripts can be written in another language such as ruby. The key concept is that the basic command (bin/up) is the same across all projects across spartan.

**Comment by bbrock25** [comment]
I'll go ahead and close this, I don't think that there's overwhelming consensus to not include these features. Thanks for fielding my questions :smile: 

@squaresurf  FWIW, I'm not opposed to bash, I'm sure it beats writing all that out in ruby. looking forward to seeing how all this develops.

**Comment by squaresurf** [comment]
Thank you @bbrock25 for your input :smile:
